### ISSUE TITLE
No module named 'dataclasses'

### ISSUE THREAD

**Issue by kemecs** [StewLG/check_truenas_extended_play#10]
 pip install dataclasses
Requirement already satisfied: dataclasses in /usr/local/lib/python2.7/dist-packages

 python3 check_truenas.py

Traceback (most recent call last):
  File "check_truenas.py", line 34, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

**Comment by StewLG** [comment]
I haven't seen this before. I'm not a Python expert, so this is guesswork. 

The pip command output references a Python 2.7 library. Then you deliberately run python3, so maybe pip is trying to work against a parallel Python 2.x install?

What happens when you just run "python"? Do you get Python 2.7?
 
How about deliberately invoking python3 when you do the dataclasses install. Here's an example I just ran:

```
root@waffle:/# python3 -m pip install dataclasses
Collecting dataclasses
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Installing collected packages: dataclasses
Successfully installed dataclasses-0.6
root@waffle:/# 
```

**Comment by kemecs** [comment]
root@monitoring:~# python3 -m pip install dataclasses
/usr/bin/python3: No module named pip

**Comment by StewLG** [comment]
I feel like this issue is related to this one:

https://github.com/StewLG/check_truenas_extended_play/issues/11

I would appreciate it if you could try the version I've put here:

https://github.com/StewLG/check_truenas_extended_play/blob/Add_Python_version_check/check_truenas_extended_play.py

Sorry for missing your response until now!

**Comment by StewLG** [comment]
I believe this is due to you not running Python 3.7 or later, where dataclass is introduced. The error you get when running an older version of Python is very poor. I've tried to improve this, but have not been very successful.

Are you running Python 3.7 or later?

**Comment by StewLG** [comment]
I am closing this. Again, I believe the issue was the user was not running Python 3.7 or later. Please re-open if you need any more help.
