### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by duven87** [StewLG/check_truenas_extended_play#11]
root@coltmon:/usr/lib/nagios/plugins# ./check_truenas_extended_play.py 
```
  File "./check_truenas_extended_play.py", line 43
    ZpoolName: str
             ^
SyntaxError: invalid syntax
```
Hello! can someone tell me why? it doesn't ask me for any library, plugin, etc. it just says that the syntax is wrong. 
(Debian 9 + python3.5)

**Comment by duven87** [comment]
I have observed that from my workstation with Mint 20.3 it works (python 3.8.10)  but from the Icinga server with Debian 9 it doesn't... I must be missing some package or some python dependency for it not to be considered a syntax error.
The version installed on the server is 3.5.3. Does it need a newer one?

**Comment by StewLG** [comment]
I believe the issue is that the dataclasses module is part of Python 3.7, and you are running 3.5. 

https://www.tutorialspoint.com/data-classes-in-python-dataclasses

The script didn't give you any useful feedback about this, however, so it's hardly your fault you were confused.

I've made a prospective change to the script so that it will complain if run using a Python version below 3.7. I would appreciate it if you could test it on both your Python 3.8 setup and your Python 3.5 setup before you upgrade your Icinga Server's version.

https://github.com/StewLG/check_truenas_extended_play/blob/Add_Python_version_check/check_truenas_extended_play.py

Let me know if it works as expected.

**Comment by duven87** [comment]
Hi! thanks for ur feedback!
yesterday I upgrated the satellite to 3.7.3 and the original script works but the server master its still with 3.5.3 and the second script no works unfortunately
```
root@coltmaster:/usr/lib/nagios/plugins# ./check_truenas2.py 
  File "./check_truenas2.py", line 48
    ZpoolName: str
             ^
SyntaxError: invalid syntax
```

**Comment by StewLG** [comment]
I've looked into this and although I have added Python version checking code at the top of the script now, it's not very helpful.

This is because the script won't compile properly under older versions of Python. So, the error you are seeing isn't easily avoided.

I have documented the Python version required, as well as your error (which I can confirm under an old Python 3 version). I'm hoping this will help anyone who is confused in the future.

I think we understand the source of this error, and I've done what little I can about it. Do you agree we can close this particular issue?

**Comment by duven87** [comment]
Yes ok, thanks anyway :)
